#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Aug 27 10:50:42 2021

@author: alexandraherve
"""

day = "Thursday"
print(type(day))
day = 32.5
print(type(day))
day = 19
print(type(day))
day = 3j
print(type(day))

expenses1 = input("How much did you spend on Sunday?")
expenses2 = input("How much did you spend on Monday?")
#total$ is a bad variable name because of $
#2 is a bad vaiable because it doesnt begin with
#total spent is a bad variable becuase of space
total = float(expenses1) + float(expenses2)


print("You spent: $" + "{:.2f}".format(total))

#Casting
x = int(1)
y = int(2.8)
z = int("3")
print(x, end=" ")
print(y, end= " ")
print(z, end= " ")

x = float(1)
y = float(2.8)
z = float("3")
w = float("4.2")
print(x, end=" ")
print(y, end= " ")
print(z, end= " ")
print(w)

x = str("s1")
y = str(2)
z = str(3.0)
print(x)
print(y)
print(z)

x = complex(5)
print(x)

#Take a radius as an input. Print out the area of that circle
#Take a radius as an input. Print out the volume sphere.
#Both answers should be to 4 decimal places printed.
